### ISSUE TITLE
Deleting linked entity reports internal server error.

### ISSUE THREAD

**Issue by pistolbarrel** [pistolbarrel/moviedbweb#3]
Need to add check before attempting to delete. Return appropriate value and reason.

**Comment by pistolbarrel** [comment]
This is the relevant part of the thread dump:
`2022-08-07 07:28:05.867  WARN 13320 --- [nio-8080-exec-3] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 1451, SQLState: 2300
0
2022-08-07 07:28:05.868 ERROR 13320 --- [nio-8080-exec-3] o.h.engine.jdbc.spi.SqlExceptionHelper   : Cannot delete or update a paren
t row: a foreign key constraint fails (`new_schema`.`movie_collection`, CONSTRAINT `FKb6pi5rd7t9ml3l1rbaa8w1tgh` FOREIGN KEY (`colle
ction_id`) REFERENCES `collection` (`collection_id`))
2022-08-07 07:28:05.869  INFO 13320 --- [nio-8080-exec-3] o.h.e.j.b.internal.AbstractBatchImpl     : HHH000010: On release of batch
it still contained JDBC statements
2022-08-07 07:28:05.912 ERROR 13320 --- [nio-8080-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [
dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.D
ataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.excepti
on.ConstraintViolationException: could not execute statement] with root cause

java.sql.SQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`new_schema
`.`movie_collection`, CONSTRAINT `FKb6pi5rd7t9ml3l1rbaa8w1tgh` FOREIGN KEY (`collection_id`) REFERENCES `collection` (`collection_id
`))
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117) ~[mysql-connector-java-8.0.28.jar!/:8.0.28]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-jav
a-8.0.28.jar!/:8.0.28]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.28
.jar!/:8.0.28]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1098) ~[mysql-connector-java
-8.0.28.jar!/:8.0.28]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1046) ~[mysql-connector-java
-8.0.28.jar!/:8.0.28]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1371) ~[mysql-connector-java-8.
0.28.jar!/:8.0.28]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1031) ~[mysql-connector-java-8.0.28.
jar!/:8.0.28]
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HikariCP-4.0.3.jar!/:na]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariCP-4.0.3.jar
!/:na]`

**Comment by pistolbarrel** [comment]
This has been fixed.
